### ISSUE TITLE
 CUDA error: out of memory

### ISSUE THREAD

**Issue by weixk2015** [sunghoonim/DPSNet#5]
When I test on a 12GB TITAN X GPU, I got this 
Traceback (most recent call last):
  File "test.py", line 127, in <module>
    main()
  File "test.py", line 90, in main
    output_depth = dpsnet(tgt_img_var, ref_imgs_var, pose, intrinsics_var, intrinsics_inv_var)
  File "/home/weixk15/anaconda3/envs/DU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weixk15/work/DPSNet/models/PSNet.py", line 106, in forward
    cost0 = self.dres1(cost0) + cost0
  File "/home/weixk15/anaconda3/envs/DU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weixk15/anaconda3/envs/DU/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/weixk15/anaconda3/envs/DU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weixk15/anaconda3/envs/DU/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/weixk15/anaconda3/envs/DU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weixk15/anaconda3/envs/DU/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 421, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by weixk2015** [comment]
oh, sorry, pytorch version is too high
